#!/bin/bash

case $1 in
clear)
    rm * target/classes
    rm target/App.jar
    ;;

build)
    javac -cp serc -d target/classes src/App.java
    ;;

package)
    jar -cfe App.jar App App.class
    ;;

run)
    java App
    jj
esac